export const products = [
  {
    id: 1,
    name: "Apple iPhone 15 Pro",
    description: "De nieuwste iPhone met titanium behuizing en A17 Pro chip",
    price: 1199,
    category: "Smartphones",
    image: "/images/iphone-15-pro.jpg",
    inStock: true,
  },
  {
    id: 2,
    name: "Samsung Galaxy S24 Ultra",
    description: "Premium Android telefoon met S Pen en geweldige camera",
    price: 1299,
    category: "Smartphones",
    image: "/images/galaxy-s24.jpg",
    inStock: true,
  },
  {
    id: 3,
    name: "MacBook Pro 14-inch",
    description: "Krachtige laptop met M3 Pro chip voor professioneel gebruik",
    price: 1999,
    category: "Laptops",
    image: "/images/macbook-pro.jpg",
    inStock: true,
  },
  {
    id: 4,
    name: "Dell XPS 13",
    description: "Dunne en lichte Windows laptop met InfinityEdge display",
    price: 1299,
    category: "Laptops",
    image: "/images/dell-xps.jpg",
    inStock: false,
  },
  {
    id: 5,
    name: "Sony WH-1000XM5",
    description: "Premium noise cancelling hoofdtelefoon met uitstekende geluidskwaliteit",
    price: 399,
    category: "Audio",
    image: "/images/sony-headphones.jpg",
    inStock: true,
  },
  {
    id: 6,
    name: "AirPods Pro 2",
    description: "Draadloze oordopjes met actieve noise cancelling",
    price: 249,
    category: "Audio",
    image: "/images/airpods-pro.jpg",
    inStock: true,
  },
  {
    id: 7,
    name: "iPad Air",
    description: "Veelzijdige tablet met M1 chip voor werk en entertainment",
    price: 599,
    category: "Tablets",
    image: "/images/ipad-air.jpg",
    inStock: true,
  },
  {
    id: 8,
    name: "Microsoft Surface Pro 9",
    description: "2-in-1 tablet met laptop prestaties en Windows 11",
    price: 999,
    category: "Tablets",
    image: "/images/surface-pro.jpg",
    inStock: true,
  },
  {
    id: 9,
    name: "Nintendo Switch OLED",
    description: "Hybrid gameconsole met OLED scherm voor thuis en onderweg",
    price: 349,
    category: "Gaming",
    image: "/images/switch-oled.jpg",
    inStock: true,
  },
  {
    id: 10,
    name: "PlayStation 5",
    description: "Next-gen gameconsole met 4K gaming en snelle SSD",
    price: 499,
    category: "Gaming",
    image: "/images/ps5.jpg",
    inStock: false,
  },
  {
    id: 11,
    name: "Apple Watch Series 9",
    description: "Smartwatch met gezondheidsfuncties en fitness tracking",
    price: 429,
    category: "Wearables",
    image: "/images/apple-watch.jpg",
    inStock: true,
  },
  {
    id: 12,
    name: "Samsung Galaxy Watch 6",
    description: "Android smartwatch met uitgebreide gezondheidsmonitoring",
    price: 349,
    category: "Wearables",
    image: "/images/galaxy-watch.jpg",
    inStock: true,
  },
];